language: php

php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

before_script:
    - travis_retry composer require satooshi/php-coveralls '~1.0'
    - travis_retry composer require phpunit/phpunit": "4.*"
    - travis_retry composer install --no-ansi --no-dev --no-interaction --no-progress --no-scripts --optimize-autoloader

script:
  - ant travis

after_success:
  - travis_retry php vendor/bin/coveralls -v
