language: php

sudo: false

cache:
  directories:
        - $HOME/.composer/cache

php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

install:
  - composer require satooshi/php-coveralls:~0.6@stable --no-update

before_script:
#    - travis_retry composer require satooshi/php-coveralls '^0.6' --update-no-dev
#    - travis_retry composer require phpunit/phpunit '4.*' --update-no-dev
  - travis_retry composer update --no-ansi --no-dev --no-interaction --no-progress --no-scripts --optimize-autoloader

script:
  - ant travis

after_success:
  - travis_retry php ./vendor/bin/coveralls -v

#after_success:
#  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/coveralls -v; fi;'
