language: php

php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

before_script:
    - travis_retry composer self-update
    - travis_retry composer --prefer-source --dev install --no-interaction

script:
  - ant quick-build

after_success:
  - travis_retry php vendor/bin/coveralls -v
