language: php
php:
    - 7.0
    - 5.6
    - 5.5
    - 5.4

before_script:
    - travis_retry composer self-update
    - travis_retry composer --prefer-source --dev install

script:
  - mkdir -p build/logs
  - phpunit --configuration phpunit-travis.xml
