language: php

sudo: false

cache:
  directories:
        - $HOME/.composer/cache

php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly

install:
  -

before_script:
 - if [ "$TRAVIS_PHP_VERSION" = "5.6" ]; then travis_retry composer require satooshi/php-coveralls:~0.6@stable --no-update ; fi

script:
  - ant travis

after_success:
 - if [ "$TRAVIS_PHP_VERSION" = "5.6" ]; then travis_retry php vendor/bin/coveralls -v; fi
